from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.dataspace_search_filter_configuration_out import DataspaceSearchFilterConfigurationOut
    from ..models.dataspace_search_request_get_out_highlight_keywords_type_0 import (
        DataspaceSearchRequestGetOutHighlightKeywordsType0,
    )
    from ..models.dataspace_search_tag_config_out import DataspaceSearchTagConfigOut
    from ..models.field_condition_input import FieldConditionInput
    from ..models.user_metadata import UserMetadata


T = TypeVar("T", bound="DataspaceSearchRequestGetOut")


@_attrs_define
class DataspaceSearchRequestGetOut:
    """Output schema for a single search request

    Attributes:
        tag (DataspaceSearchTagConfigOut | None):
        filters (list[DataspaceSearchFilterConfigurationOut]):
        conditions (list[FieldConditionInput]):
        created_by (UserMetadata):
        updated_by (UserMetadata):
        created (datetime.datetime):
        updated (datetime.datetime):
        id (None | Unset | UUID):
        keywords (None | str | Unset): Search keywords entered by user
        highlight_keywords (DataspaceSearchRequestGetOutHighlightKeywordsType0 | None | Unset): List of keywords
            generated by splitting keywords on whitespace
        is_saved (bool | Unset): Whether this search request is saved by the user Default: False.
    """

    tag: DataspaceSearchTagConfigOut | None
    filters: list[DataspaceSearchFilterConfigurationOut]
    conditions: list[FieldConditionInput]
    created_by: UserMetadata
    updated_by: UserMetadata
    created: datetime.datetime
    updated: datetime.datetime
    id: None | Unset | UUID = UNSET
    keywords: None | str | Unset = UNSET
    highlight_keywords: DataspaceSearchRequestGetOutHighlightKeywordsType0 | None | Unset = UNSET
    is_saved: bool | Unset = False
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.dataspace_search_request_get_out_highlight_keywords_type_0 import (
            DataspaceSearchRequestGetOutHighlightKeywordsType0,
        )
        from ..models.dataspace_search_tag_config_out import DataspaceSearchTagConfigOut

        tag: dict[str, Any] | None
        if isinstance(self.tag, DataspaceSearchTagConfigOut):
            tag = self.tag.to_dict()
        else:
            tag = self.tag

        filters = []
        for filters_item_data in self.filters:
            filters_item = filters_item_data.to_dict()
            filters.append(filters_item)

        conditions = []
        for conditions_item_data in self.conditions:
            conditions_item = conditions_item_data.to_dict()
            conditions.append(conditions_item)

        created_by = self.created_by.to_dict()

        updated_by = self.updated_by.to_dict()

        created = self.created.isoformat()

        updated = self.updated.isoformat()

        id: None | str | Unset
        if isinstance(self.id, Unset):
            id = UNSET
        elif isinstance(self.id, UUID):
            id = str(self.id)
        else:
            id = self.id

        keywords: None | str | Unset
        if isinstance(self.keywords, Unset):
            keywords = UNSET
        else:
            keywords = self.keywords

        highlight_keywords: dict[str, Any] | None | Unset
        if isinstance(self.highlight_keywords, Unset):
            highlight_keywords = UNSET
        elif isinstance(self.highlight_keywords, DataspaceSearchRequestGetOutHighlightKeywordsType0):
            highlight_keywords = self.highlight_keywords.to_dict()
        else:
            highlight_keywords = self.highlight_keywords

        is_saved = self.is_saved

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "tag": tag,
                "filters": filters,
                "conditions": conditions,
                "created_by": created_by,
                "updated_by": updated_by,
                "created": created,
                "updated": updated,
            }
        )
        if id is not UNSET:
            field_dict["id"] = id
        if keywords is not UNSET:
            field_dict["keywords"] = keywords
        if highlight_keywords is not UNSET:
            field_dict["highlight_keywords"] = highlight_keywords
        if is_saved is not UNSET:
            field_dict["is_saved"] = is_saved

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.dataspace_search_filter_configuration_out import DataspaceSearchFilterConfigurationOut
        from ..models.dataspace_search_request_get_out_highlight_keywords_type_0 import (
            DataspaceSearchRequestGetOutHighlightKeywordsType0,
        )
        from ..models.dataspace_search_tag_config_out import DataspaceSearchTagConfigOut
        from ..models.field_condition_input import FieldConditionInput
        from ..models.user_metadata import UserMetadata

        d = dict(src_dict)

        def _parse_tag(data: object) -> DataspaceSearchTagConfigOut | None:
            if data is None:
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                tag_type_0 = DataspaceSearchTagConfigOut.from_dict(data)

                return tag_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(DataspaceSearchTagConfigOut | None, data)

        tag = _parse_tag(d.pop("tag"))

        filters = []
        _filters = d.pop("filters")
        for filters_item_data in _filters:
            filters_item = DataspaceSearchFilterConfigurationOut.from_dict(filters_item_data)

            filters.append(filters_item)

        conditions = []
        _conditions = d.pop("conditions")
        for conditions_item_data in _conditions:
            conditions_item = FieldConditionInput.from_dict(conditions_item_data)

            conditions.append(conditions_item)

        created_by = UserMetadata.from_dict(d.pop("created_by"))

        updated_by = UserMetadata.from_dict(d.pop("updated_by"))

        created = isoparse(d.pop("created"))

        updated = isoparse(d.pop("updated"))

        def _parse_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                id_type_0 = UUID(data)

                return id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        id = _parse_id(d.pop("id", UNSET))

        def _parse_keywords(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        keywords = _parse_keywords(d.pop("keywords", UNSET))

        def _parse_highlight_keywords(
            data: object,
        ) -> DataspaceSearchRequestGetOutHighlightKeywordsType0 | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                highlight_keywords_type_0 = DataspaceSearchRequestGetOutHighlightKeywordsType0.from_dict(data)

                return highlight_keywords_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(DataspaceSearchRequestGetOutHighlightKeywordsType0 | None | Unset, data)

        highlight_keywords = _parse_highlight_keywords(d.pop("highlight_keywords", UNSET))

        is_saved = d.pop("is_saved", UNSET)

        dataspace_search_request_get_out = cls(
            tag=tag,
            filters=filters,
            conditions=conditions,
            created_by=created_by,
            updated_by=updated_by,
            created=created,
            updated=updated,
            id=id,
            keywords=keywords,
            highlight_keywords=highlight_keywords,
            is_saved=is_saved,
        )

        dataspace_search_request_get_out.additional_properties = d
        return dataspace_search_request_get_out

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
