from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.execution_process_response import ExecutionProcessResponse
    from ..models.executions_review_status_details import ExecutionsReviewStatusDetails
    from ..models.user_metadata import UserMetadata


T = TypeVar("T", bound="ExecutionResponse")


@_attrs_define
class ExecutionResponse:
    """Serializer for Execution details

    Attributes:
        review_status (ExecutionsReviewStatusDetails): Details about execution review statuses within an execution group
        approvals_count (int):
        process_details (ExecutionProcessResponse): Process details within an execution group
        launched_by (UserMetadata):
        created (datetime.datetime):
        updated (datetime.datetime):
        reviewed_by_names (list[str] | Unset):
        id (None | Unset | UUID):
        start_time (datetime.datetime | None | Unset):
        end_time (datetime.datetime | None | Unset):
        is_system_generated (bool | Unset): Indicates if this execution was generated by the system Default: False.
        requested_approval_count (int | Unset): Total number of approval steps for this execution that the user/agent
            has been requested to review Default: 0.
        status (str | Unset): The status of the execution (e.g., pending, completed, failed) Default: 'pending'.
    """

    review_status: ExecutionsReviewStatusDetails
    approvals_count: int
    process_details: ExecutionProcessResponse
    launched_by: UserMetadata
    created: datetime.datetime
    updated: datetime.datetime
    reviewed_by_names: list[str] | Unset = UNSET
    id: None | Unset | UUID = UNSET
    start_time: datetime.datetime | None | Unset = UNSET
    end_time: datetime.datetime | None | Unset = UNSET
    is_system_generated: bool | Unset = False
    requested_approval_count: int | Unset = 0
    status: str | Unset = "pending"
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        review_status = self.review_status.to_dict()

        approvals_count = self.approvals_count

        process_details = self.process_details.to_dict()

        launched_by = self.launched_by.to_dict()

        created = self.created.isoformat()

        updated = self.updated.isoformat()

        reviewed_by_names: list[str] | Unset = UNSET
        if not isinstance(self.reviewed_by_names, Unset):
            reviewed_by_names = self.reviewed_by_names

        id: None | str | Unset
        if isinstance(self.id, Unset):
            id = UNSET
        elif isinstance(self.id, UUID):
            id = str(self.id)
        else:
            id = self.id

        start_time: None | str | Unset
        if isinstance(self.start_time, Unset):
            start_time = UNSET
        elif isinstance(self.start_time, datetime.datetime):
            start_time = self.start_time.isoformat()
        else:
            start_time = self.start_time

        end_time: None | str | Unset
        if isinstance(self.end_time, Unset):
            end_time = UNSET
        elif isinstance(self.end_time, datetime.datetime):
            end_time = self.end_time.isoformat()
        else:
            end_time = self.end_time

        is_system_generated = self.is_system_generated

        requested_approval_count = self.requested_approval_count

        status = self.status

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "review_status": review_status,
                "approvals_count": approvals_count,
                "process_details": process_details,
                "launched_by": launched_by,
                "created": created,
                "updated": updated,
            }
        )
        if reviewed_by_names is not UNSET:
            field_dict["reviewed_by_names"] = reviewed_by_names
        if id is not UNSET:
            field_dict["id"] = id
        if start_time is not UNSET:
            field_dict["start_time"] = start_time
        if end_time is not UNSET:
            field_dict["end_time"] = end_time
        if is_system_generated is not UNSET:
            field_dict["is_system_generated"] = is_system_generated
        if requested_approval_count is not UNSET:
            field_dict["requested_approval_count"] = requested_approval_count
        if status is not UNSET:
            field_dict["status"] = status

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.execution_process_response import ExecutionProcessResponse
        from ..models.executions_review_status_details import ExecutionsReviewStatusDetails
        from ..models.user_metadata import UserMetadata

        d = dict(src_dict)
        review_status = ExecutionsReviewStatusDetails.from_dict(d.pop("review_status"))

        approvals_count = d.pop("approvals_count")

        process_details = ExecutionProcessResponse.from_dict(d.pop("process_details"))

        launched_by = UserMetadata.from_dict(d.pop("launched_by"))

        created = isoparse(d.pop("created"))

        updated = isoparse(d.pop("updated"))

        reviewed_by_names = cast(list[str], d.pop("reviewed_by_names", UNSET))

        def _parse_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                id_type_0 = UUID(data)

                return id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        id = _parse_id(d.pop("id", UNSET))

        def _parse_start_time(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                start_time_type_0 = isoparse(data)

                return start_time_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        start_time = _parse_start_time(d.pop("start_time", UNSET))

        def _parse_end_time(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                end_time_type_0 = isoparse(data)

                return end_time_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        end_time = _parse_end_time(d.pop("end_time", UNSET))

        is_system_generated = d.pop("is_system_generated", UNSET)

        requested_approval_count = d.pop("requested_approval_count", UNSET)

        status = d.pop("status", UNSET)

        execution_response = cls(
            review_status=review_status,
            approvals_count=approvals_count,
            process_details=process_details,
            launched_by=launched_by,
            created=created,
            updated=updated,
            reviewed_by_names=reviewed_by_names,
            id=id,
            start_time=start_time,
            end_time=end_time,
            is_system_generated=is_system_generated,
            requested_approval_count=requested_approval_count,
            status=status,
        )

        execution_response.additional_properties = d
        return execution_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
