from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.execution_status_count_details import ExecutionStatusCountDetails
    from ..models.execution_status_details import ExecutionStatusDetails
    from ..models.executions_review_status_details import ExecutionsReviewStatusDetails
    from ..models.user_metadata import UserMetadata


T = TypeVar("T", bound="ExecutionGroupDetailResponse")


@_attrs_define
class ExecutionGroupDetailResponse:
    """Serializer for ExecutionGroup details

    Attributes:
        created_by (UserMetadata):
        updated_by (UserMetadata):
        launched_by (UserMetadata):
        approvals_count (int):
        executions_count (int):
        status_details (ExecutionStatusDetails): Details about execution statuses within an execution group
        execution_status_details (ExecutionStatusCountDetails): Counts of executions by status within an execution group
        review_status (ExecutionsReviewStatusDetails): Details about execution review statuses within an execution group
        created (datetime.datetime):
        updated (datetime.datetime):
        tektome_token (float | None | Unset):
        reviewed_by_names (list[str] | Unset):
        id (None | Unset | UUID):
        memo (None | str | Unset): A description of the purpose of this execution group
        status (str | Unset): The status of the execution group (e.g., Initializing, Running, Completed, Failed)
            Default: 'initializing'.
        is_system_generated (bool | Unset): Indicates if this execution group was generated by the system Default:
            False.
        auto_approved_output (bool | Unset): Indicates if the outputs will be auto-approved Default: False.
        start_time (datetime.datetime | None | Unset):
        end_time (datetime.datetime | None | Unset):
    """

    created_by: UserMetadata
    updated_by: UserMetadata
    launched_by: UserMetadata
    approvals_count: int
    executions_count: int
    status_details: ExecutionStatusDetails
    execution_status_details: ExecutionStatusCountDetails
    review_status: ExecutionsReviewStatusDetails
    created: datetime.datetime
    updated: datetime.datetime
    tektome_token: float | None | Unset = UNSET
    reviewed_by_names: list[str] | Unset = UNSET
    id: None | Unset | UUID = UNSET
    memo: None | str | Unset = UNSET
    status: str | Unset = "initializing"
    is_system_generated: bool | Unset = False
    auto_approved_output: bool | Unset = False
    start_time: datetime.datetime | None | Unset = UNSET
    end_time: datetime.datetime | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        created_by = self.created_by.to_dict()

        updated_by = self.updated_by.to_dict()

        launched_by = self.launched_by.to_dict()

        approvals_count = self.approvals_count

        executions_count = self.executions_count

        status_details = self.status_details.to_dict()

        execution_status_details = self.execution_status_details.to_dict()

        review_status = self.review_status.to_dict()

        created = self.created.isoformat()

        updated = self.updated.isoformat()

        tektome_token: float | None | Unset
        if isinstance(self.tektome_token, Unset):
            tektome_token = UNSET
        else:
            tektome_token = self.tektome_token

        reviewed_by_names: list[str] | Unset = UNSET
        if not isinstance(self.reviewed_by_names, Unset):
            reviewed_by_names = self.reviewed_by_names

        id: None | str | Unset
        if isinstance(self.id, Unset):
            id = UNSET
        elif isinstance(self.id, UUID):
            id = str(self.id)
        else:
            id = self.id

        memo: None | str | Unset
        if isinstance(self.memo, Unset):
            memo = UNSET
        else:
            memo = self.memo

        status = self.status

        is_system_generated = self.is_system_generated

        auto_approved_output = self.auto_approved_output

        start_time: None | str | Unset
        if isinstance(self.start_time, Unset):
            start_time = UNSET
        elif isinstance(self.start_time, datetime.datetime):
            start_time = self.start_time.isoformat()
        else:
            start_time = self.start_time

        end_time: None | str | Unset
        if isinstance(self.end_time, Unset):
            end_time = UNSET
        elif isinstance(self.end_time, datetime.datetime):
            end_time = self.end_time.isoformat()
        else:
            end_time = self.end_time

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "created_by": created_by,
                "updated_by": updated_by,
                "launched_by": launched_by,
                "approvals_count": approvals_count,
                "executions_count": executions_count,
                "status_details": status_details,
                "execution_status_details": execution_status_details,
                "review_status": review_status,
                "created": created,
                "updated": updated,
            }
        )
        if tektome_token is not UNSET:
            field_dict["tektome_token"] = tektome_token
        if reviewed_by_names is not UNSET:
            field_dict["reviewed_by_names"] = reviewed_by_names
        if id is not UNSET:
            field_dict["id"] = id
        if memo is not UNSET:
            field_dict["memo"] = memo
        if status is not UNSET:
            field_dict["status"] = status
        if is_system_generated is not UNSET:
            field_dict["is_system_generated"] = is_system_generated
        if auto_approved_output is not UNSET:
            field_dict["auto_approved_output"] = auto_approved_output
        if start_time is not UNSET:
            field_dict["start_time"] = start_time
        if end_time is not UNSET:
            field_dict["end_time"] = end_time

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.execution_status_count_details import ExecutionStatusCountDetails
        from ..models.execution_status_details import ExecutionStatusDetails
        from ..models.executions_review_status_details import ExecutionsReviewStatusDetails
        from ..models.user_metadata import UserMetadata

        d = dict(src_dict)
        created_by = UserMetadata.from_dict(d.pop("created_by"))

        updated_by = UserMetadata.from_dict(d.pop("updated_by"))

        launched_by = UserMetadata.from_dict(d.pop("launched_by"))

        approvals_count = d.pop("approvals_count")

        executions_count = d.pop("executions_count")

        status_details = ExecutionStatusDetails.from_dict(d.pop("status_details"))

        execution_status_details = ExecutionStatusCountDetails.from_dict(d.pop("execution_status_details"))

        review_status = ExecutionsReviewStatusDetails.from_dict(d.pop("review_status"))

        created = isoparse(d.pop("created"))

        updated = isoparse(d.pop("updated"))

        def _parse_tektome_token(data: object) -> float | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(float | None | Unset, data)

        tektome_token = _parse_tektome_token(d.pop("tektome_token", UNSET))

        reviewed_by_names = cast(list[str], d.pop("reviewed_by_names", UNSET))

        def _parse_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                id_type_0 = UUID(data)

                return id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        id = _parse_id(d.pop("id", UNSET))

        def _parse_memo(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        memo = _parse_memo(d.pop("memo", UNSET))

        status = d.pop("status", UNSET)

        is_system_generated = d.pop("is_system_generated", UNSET)

        auto_approved_output = d.pop("auto_approved_output", UNSET)

        def _parse_start_time(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                start_time_type_0 = isoparse(data)

                return start_time_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        start_time = _parse_start_time(d.pop("start_time", UNSET))

        def _parse_end_time(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                end_time_type_0 = isoparse(data)

                return end_time_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        end_time = _parse_end_time(d.pop("end_time", UNSET))

        execution_group_detail_response = cls(
            created_by=created_by,
            updated_by=updated_by,
            launched_by=launched_by,
            approvals_count=approvals_count,
            executions_count=executions_count,
            status_details=status_details,
            execution_status_details=execution_status_details,
            review_status=review_status,
            created=created,
            updated=updated,
            tektome_token=tektome_token,
            reviewed_by_names=reviewed_by_names,
            id=id,
            memo=memo,
            status=status,
            is_system_generated=is_system_generated,
            auto_approved_output=auto_approved_output,
            start_time=start_time,
            end_time=end_time,
        )

        execution_group_detail_response.additional_properties = d
        return execution_group_detail_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
